name: SilhouetteDance Build

on:
  push:
    paths:
      - "**.cs"
    branches: ["master"]
  pull_request:
    branches: ["master"]
    paths:
      - "**.cs"

  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest

    strategy:
      matrix:
        runtimeIdentifier: [ win-x64, win-x86 ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Build SilhouetteDance
        shell: powershell
        run: |
          dotnet publish SilhouetteDance.csproj --no-self-contained -p:PublishSingleFile=true -p:IncludeContentInSingleFile=true -p:RuntimeIdentifier=${{ matrix.runtimeIdentifier }}

      - name: Create directories
        shell: powershell
        run: |
          md bin/Debug/net6.0/${{ matrix.runtimeIdentifier }}/publish/Lagrange
          md bin/Debug/net6.0/${{ matrix.runtimeIdentifier }}/publish/prompts

      - name: Upload binary files(${{ matrix.runtimeIdentifier }})
        uses: actions/upload-artifact@v3
        with:
          name: Lagrange.HikawaHina_${{ matrix.runtimeIdentifier }}
          path: bin/Debug/net6.0/${{ matrix.runtimeIdentifier }}/publish
